version: '3.6'

networks:
  ollama:

services:
  ollama:
    image: ollama/ollama
    networks:
      - ollama
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - '127.0.0.1:11434:11434'

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    volumes:
      - ./data/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - '127.0.0.1:8504:8080'
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama

  packet_buddy:
    image: johncapobianco/packet_buddy:packet_buddy
    container_name: packet_buddy
    restart: always
    environment:
      - OLLAMA_URL=http://ollama:11434
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "127.0.0.1:8505:8505"
    volumes:
      - ./config.toml:/root/.streamlit/config.toml
    depends_on:
      - ollama
    networks:
      - ollama
#    deploy:
#      resources:
#        reservations:
#          devices:
#          - driver: nvidia
#            count: 1
#            capabilities: [gpu] 
